#!/bin/bash

# Define common environment variables here, then "source"
# this file in the several bash scripts.
# Chris Joakim, Microsoft, 2019/04/13

export LOCAL_MONGODB_URL=localhost:27017/demo
export LOCAL_MONGODB_HOST=localhost
export LOCAL_MONGODB_PORT=27017
export LOCAL_MONGODB_DB=hackathon
export LOCAL_MONGODB_COLL=airports

export AZURE_MONGODB_CONN_STR=$AZURE_COSMOSDB_MONGODB_CONN_STRING
export AZURE_MONGODB_HOST=$AZURE_COSMOSDB_MONGODB_HOST
export AZURE_MONGODB_PORT=$AZURE_COSMOSDB_MONGODB_PORT
export AZURE_MONGODB_ACCT=cjoakimcosmosdbmongo
export AZURE_MONGODB_DB=hackathon
export AZURE_MONGODB_COLL=airports
export AZURE_MONGODB_USER=$AZURE_COSMOSDB_MONGODB_USER
export AZURE_MONGODB_PASS=$AZURE_COSMOSDB_MONGODB_PASS

# These environment variables are also set on my workstation:
# AZURE_COSMOSDB_SQLDB_ACCT
# AZURE_COSMOSDB_SQLDB_COLLNAME
# AZURE_COSMOSDB_SQLDB_CONN_STRING
# AZURE_COSMOSDB_SQLDB_DBNAME
# AZURE_COSMOSDB_SQLDB_KEY
# AZURE_COSMOSDB_SQLDB_URI

# env | grep LOCAL_MONGODB_
# env | grep AZURE_MONGODB_
# env | grep AZURE_COSMOSDB_SQLDB_
