#!/bin/bash
# This script was generated by classpath.py.
# It can be executed to do a "jar -xvf" for each jar in the
# CLASSPATH, so as to produce a list of all dependent classes for analysis.
# Chris Joakim, 2018/10/23


echo "JAR-FILE: /Users/cjoakim/.m2/repository/com/microsoft/azure/azure/1.17.0/azure-1.17.0.jar" >> doc/jar_contents.txt
jar -tvf /Users/cjoakim/.m2/repository/com/microsoft/azure/azure/1.17.0/azure-1.17.0.jar >> doc/jar_contents.txt

echo "JAR-FILE: /Users/cjoakim/.m2/repository/com/microsoft/azure/azure-client-runtime/1.6.3/azure-client-runtime-1.6.3.jar" >> doc/jar_contents.txt
jar -tvf /Users/cjoakim/.m2/repository/com/microsoft/azure/azure-client-runtime/1.6.3/azure-client-runtime-1.6.3.jar >> doc/jar_contents.txt

echo "JAR-FILE: /Users/cjoakim/.m2/repository/com/microsoft/azure/azure-client-authentication/1.6.3/azure-client-authentication-1.6.3.jar" >> doc/jar_contents.txt
jar -tvf /Users/cjoakim/.m2/repository/com/microsoft/azure/azure-client-authentication/1.6.3/azure-client-authentication-1.6.3.jar >> doc/jar_contents.txt

echo "JAR-FILE: /Users/cjoakim/.m2/repository/com/microsoft/azure/azure-annotations/1.7.0/azure-annotations-1.7.0.jar" >> doc/jar_contents.txt
jar -tvf /Users/cjoakim/.m2/repository/com/microsoft/azure/azure-annotations/1.7.0/azure-annotations-1.7.0.jar >> doc/jar_contents.txt

echo "JAR-FILE: /Users/cjoakim/.m2/repository/com/microsoft/azure/azure-mgmt-resources/1.17.0/azure-mgmt-resources-1.17.0.jar" >> doc/jar_contents.txt
jar -tvf /Users/cjoakim/.m2/repository/com/microsoft/azure/azure-mgmt-resources/1.17.0/azure-mgmt-resources-1.17.0.jar >> doc/jar_contents.txt

echo "JAR-FILE: /Users/cjoakim/.m2/repository/com/microsoft/azure/azure-mgmt-storage/1.17.0/azure-mgmt-storage-1.17.0.jar" >> doc/jar_contents.txt
jar -tvf /Users/cjoakim/.m2/repository/com/microsoft/azure/azure-mgmt-storage/1.17.0/azure-mgmt-storage-1.17.0.jar >> doc/jar_contents.txt

echo "JAR-FILE: /Users/cjoakim/.m2/repository/com/microsoft/azure/azure-mgmt-network/1.17.0/azure-mgmt-network-1.17.0.jar" >> doc/jar_contents.txt
jar -tvf /Users/cjoakim/.m2/repository/com/microsoft/azure/azure-mgmt-network/1.17.0/azure-mgmt-network-1.17.0.jar >> doc/jar_contents.txt

echo "JAR-FILE: /Users/cjoakim/.m2/repository/com/microsoft/azure/azure-mgmt-compute/1.17.0/azure-mgmt-compute-1.17.0.jar" >> doc/jar_contents.txt
jar -tvf /Users/cjoakim/.m2/repository/com/microsoft/azure/azure-mgmt-compute/1.17.0/azure-mgmt-compute-1.17.0.jar >> doc/jar_contents.txt

echo "JAR-FILE: /Users/cjoakim/.m2/repository/com/microsoft/azure/azure-mgmt-graph-rbac/1.17.0/azure-mgmt-graph-rbac-1.17.0.jar" >> doc/jar_contents.txt
jar -tvf /Users/cjoakim/.m2/repository/com/microsoft/azure/azure-mgmt-graph-rbac/1.17.0/azure-mgmt-graph-rbac-1.17.0.jar >> doc/jar_contents.txt

echo "JAR-FILE: /Users/cjoakim/.m2/repository/com/microsoft/azure/azure-mgmt-keyvault/1.17.0/azure-mgmt-keyvault-1.17.0.jar" >> doc/jar_contents.txt
jar -tvf /Users/cjoakim/.m2/repository/com/microsoft/azure/azure-mgmt-keyvault/1.17.0/azure-mgmt-keyvault-1.17.0.jar >> doc/jar_contents.txt

echo "JAR-FILE: /Users/cjoakim/.m2/repository/com/microsoft/azure/azure-mgmt-batch/1.17.0/azure-mgmt-batch-1.17.0.jar" >> doc/jar_contents.txt
jar -tvf /Users/cjoakim/.m2/repository/com/microsoft/azure/azure-mgmt-batch/1.17.0/azure-mgmt-batch-1.17.0.jar >> doc/jar_contents.txt

echo "JAR-FILE: /Users/cjoakim/.m2/repository/com/microsoft/azure/azure-mgmt-trafficmanager/1.17.0/azure-mgmt-trafficmanager-1.17.0.jar" >> doc/jar_contents.txt
jar -tvf /Users/cjoakim/.m2/repository/com/microsoft/azure/azure-mgmt-trafficmanager/1.17.0/azure-mgmt-trafficmanager-1.17.0.jar >> doc/jar_contents.txt

echo "JAR-FILE: /Users/cjoakim/.m2/repository/com/microsoft/azure/azure-mgmt-dns/1.17.0/azure-mgmt-dns-1.17.0.jar" >> doc/jar_contents.txt
jar -tvf /Users/cjoakim/.m2/repository/com/microsoft/azure/azure-mgmt-dns/1.17.0/azure-mgmt-dns-1.17.0.jar >> doc/jar_contents.txt

echo "JAR-FILE: /Users/cjoakim/.m2/repository/com/microsoft/azure/azure-mgmt-redis/1.17.0/azure-mgmt-redis-1.17.0.jar" >> doc/jar_contents.txt
jar -tvf /Users/cjoakim/.m2/repository/com/microsoft/azure/azure-mgmt-redis/1.17.0/azure-mgmt-redis-1.17.0.jar >> doc/jar_contents.txt

echo "JAR-FILE: /Users/cjoakim/.m2/repository/com/microsoft/azure/azure-mgmt-appservice/1.17.0/azure-mgmt-appservice-1.17.0.jar" >> doc/jar_contents.txt
jar -tvf /Users/cjoakim/.m2/repository/com/microsoft/azure/azure-mgmt-appservice/1.17.0/azure-mgmt-appservice-1.17.0.jar >> doc/jar_contents.txt

echo "JAR-FILE: /Users/cjoakim/.m2/repository/com/microsoft/azure/azure-storage/6.1.0/azure-storage-6.1.0.jar" >> doc/jar_contents.txt
jar -tvf /Users/cjoakim/.m2/repository/com/microsoft/azure/azure-storage/6.1.0/azure-storage-6.1.0.jar >> doc/jar_contents.txt

echo "JAR-FILE: /Users/cjoakim/.m2/repository/com/microsoft/azure/azure-mgmt-locks/1.17.0/azure-mgmt-locks-1.17.0.jar" >> doc/jar_contents.txt
jar -tvf /Users/cjoakim/.m2/repository/com/microsoft/azure/azure-mgmt-locks/1.17.0/azure-mgmt-locks-1.17.0.jar >> doc/jar_contents.txt

echo "JAR-FILE: /Users/cjoakim/.m2/repository/com/microsoft/azure/azure-mgmt-eventhub/1.17.0/azure-mgmt-eventhub-1.17.0.jar" >> doc/jar_contents.txt
jar -tvf /Users/cjoakim/.m2/repository/com/microsoft/azure/azure-mgmt-eventhub/1.17.0/azure-mgmt-eventhub-1.17.0.jar >> doc/jar_contents.txt

echo "JAR-FILE: /Users/cjoakim/.m2/repository/com/microsoft/azure/azure-mgmt-cdn/1.17.0/azure-mgmt-cdn-1.17.0.jar" >> doc/jar_contents.txt
jar -tvf /Users/cjoakim/.m2/repository/com/microsoft/azure/azure-mgmt-cdn/1.17.0/azure-mgmt-cdn-1.17.0.jar >> doc/jar_contents.txt

echo "JAR-FILE: /Users/cjoakim/.m2/repository/com/microsoft/azure/azure-mgmt-sql/1.17.0/azure-mgmt-sql-1.17.0.jar" >> doc/jar_contents.txt
jar -tvf /Users/cjoakim/.m2/repository/com/microsoft/azure/azure-mgmt-sql/1.17.0/azure-mgmt-sql-1.17.0.jar >> doc/jar_contents.txt

echo "JAR-FILE: /Users/cjoakim/.m2/repository/com/microsoft/azure/azure-mgmt-containerinstance/1.17.0/azure-mgmt-containerinstance-1.17.0.jar" >> doc/jar_contents.txt
jar -tvf /Users/cjoakim/.m2/repository/com/microsoft/azure/azure-mgmt-containerinstance/1.17.0/azure-mgmt-containerinstance-1.17.0.jar >> doc/jar_contents.txt

echo "JAR-FILE: /Users/cjoakim/.m2/repository/com/microsoft/azure/azure-mgmt-containerregistry/1.17.0/azure-mgmt-containerregistry-1.17.0.jar" >> doc/jar_contents.txt
jar -tvf /Users/cjoakim/.m2/repository/com/microsoft/azure/azure-mgmt-containerregistry/1.17.0/azure-mgmt-containerregistry-1.17.0.jar >> doc/jar_contents.txt

echo "JAR-FILE: /Users/cjoakim/.m2/repository/com/microsoft/azure/azure-mgmt-containerservice/1.17.0/azure-mgmt-containerservice-1.17.0.jar" >> doc/jar_contents.txt
jar -tvf /Users/cjoakim/.m2/repository/com/microsoft/azure/azure-mgmt-containerservice/1.17.0/azure-mgmt-containerservice-1.17.0.jar >> doc/jar_contents.txt

echo "JAR-FILE: /Users/cjoakim/.m2/repository/com/microsoft/azure/azure-mgmt-cosmosdb/1.17.0/azure-mgmt-cosmosdb-1.17.0.jar" >> doc/jar_contents.txt
jar -tvf /Users/cjoakim/.m2/repository/com/microsoft/azure/azure-mgmt-cosmosdb/1.17.0/azure-mgmt-cosmosdb-1.17.0.jar >> doc/jar_contents.txt

echo "JAR-FILE: /Users/cjoakim/.m2/repository/com/microsoft/azure/azure-mgmt-search/1.17.0/azure-mgmt-search-1.17.0.jar" >> doc/jar_contents.txt
jar -tvf /Users/cjoakim/.m2/repository/com/microsoft/azure/azure-mgmt-search/1.17.0/azure-mgmt-search-1.17.0.jar >> doc/jar_contents.txt

echo "JAR-FILE: /Users/cjoakim/.m2/repository/com/microsoft/azure/azure-mgmt-msi/1.17.0/azure-mgmt-msi-1.17.0.jar" >> doc/jar_contents.txt
jar -tvf /Users/cjoakim/.m2/repository/com/microsoft/azure/azure-mgmt-msi/1.17.0/azure-mgmt-msi-1.17.0.jar >> doc/jar_contents.txt

echo "JAR-FILE: /Users/cjoakim/.m2/repository/com/microsoft/azure/azure-mgmt-monitor/1.17.0/azure-mgmt-monitor-1.17.0.jar" >> doc/jar_contents.txt
jar -tvf /Users/cjoakim/.m2/repository/com/microsoft/azure/azure-mgmt-monitor/1.17.0/azure-mgmt-monitor-1.17.0.jar >> doc/jar_contents.txt

echo "JAR-FILE: /Users/cjoakim/.m2/repository/com/microsoft/azure/azure-mgmt-servicebus/1.17.0/azure-mgmt-servicebus-1.17.0.jar" >> doc/jar_contents.txt
jar -tvf /Users/cjoakim/.m2/repository/com/microsoft/azure/azure-mgmt-servicebus/1.17.0/azure-mgmt-servicebus-1.17.0.jar >> doc/jar_contents.txt

echo "JAR-FILE: /Users/cjoakim/.m2/repository/com/microsoft/azure/azure-mgmt-batchai/1.17.0/azure-mgmt-batchai-1.17.0.jar" >> doc/jar_contents.txt
jar -tvf /Users/cjoakim/.m2/repository/com/microsoft/azure/azure-mgmt-batchai/1.17.0/azure-mgmt-batchai-1.17.0.jar >> doc/jar_contents.txt

echo "JAR-FILE: /Users/cjoakim/.m2/repository/com/microsoft/azure/azure-documentdb/2.0.0/azure-documentdb-2.0.0.jar" >> doc/jar_contents.txt
jar -tvf /Users/cjoakim/.m2/repository/com/microsoft/azure/azure-documentdb/2.0.0/azure-documentdb-2.0.0.jar >> doc/jar_contents.txt

echo "JAR-FILE: /Users/cjoakim/.m2/repository/com/fasterxml/uuid/java-uuid-generator/3.1.4/java-uuid-generator-3.1.4.jar" >> doc/jar_contents.txt
jar -tvf /Users/cjoakim/.m2/repository/com/fasterxml/uuid/java-uuid-generator/3.1.4/java-uuid-generator-3.1.4.jar >> doc/jar_contents.txt

echo "JAR-FILE: /Users/cjoakim/.m2/repository/org/json/json/20140107/json-20140107.jar" >> doc/jar_contents.txt
jar -tvf /Users/cjoakim/.m2/repository/org/json/json/20140107/json-20140107.jar >> doc/jar_contents.txt

echo "JAR-FILE: /Users/cjoakim/.m2/repository/org/apache/commons/commons-lang3/3.5/commons-lang3-3.5.jar" >> doc/jar_contents.txt
jar -tvf /Users/cjoakim/.m2/repository/org/apache/commons/commons-lang3/3.5/commons-lang3-3.5.jar >> doc/jar_contents.txt

echo "JAR-FILE: /Users/cjoakim/.m2/repository/org/apache/httpcomponents/httpclient/4.5.2/httpclient-4.5.2.jar" >> doc/jar_contents.txt
jar -tvf /Users/cjoakim/.m2/repository/org/apache/httpcomponents/httpclient/4.5.2/httpclient-4.5.2.jar >> doc/jar_contents.txt

echo "JAR-FILE: /Users/cjoakim/.m2/repository/commons-logging/commons-logging/1.2/commons-logging-1.2.jar" >> doc/jar_contents.txt
jar -tvf /Users/cjoakim/.m2/repository/commons-logging/commons-logging/1.2/commons-logging-1.2.jar >> doc/jar_contents.txt

echo "JAR-FILE: /Users/cjoakim/.m2/repository/org/apache/httpcomponents/httpcore/4.4.6/httpcore-4.4.6.jar" >> doc/jar_contents.txt
jar -tvf /Users/cjoakim/.m2/repository/org/apache/httpcomponents/httpcore/4.4.6/httpcore-4.4.6.jar >> doc/jar_contents.txt

echo "JAR-FILE: /Users/cjoakim/.m2/repository/org/slf4j/slf4j-api/1.7.6/slf4j-api-1.7.6.jar" >> doc/jar_contents.txt
jar -tvf /Users/cjoakim/.m2/repository/org/slf4j/slf4j-api/1.7.6/slf4j-api-1.7.6.jar >> doc/jar_contents.txt

echo "JAR-FILE: /Users/cjoakim/.m2/repository/joda-time/joda-time/2.9.9/joda-time-2.9.9.jar" >> doc/jar_contents.txt
jar -tvf /Users/cjoakim/.m2/repository/joda-time/joda-time/2.9.9/joda-time-2.9.9.jar >> doc/jar_contents.txt

echo "JAR-FILE: /Users/cjoakim/.m2/repository/com/microsoft/azure/azure-cosmosdb/2.2.0/azure-cosmosdb-2.2.0.jar" >> doc/jar_contents.txt
jar -tvf /Users/cjoakim/.m2/repository/com/microsoft/azure/azure-cosmosdb/2.2.0/azure-cosmosdb-2.2.0.jar >> doc/jar_contents.txt

echo "JAR-FILE: /Users/cjoakim/.m2/repository/com/microsoft/azure/azure-cosmosdb-commons/2.2.0/azure-cosmosdb-commons-2.2.0.jar" >> doc/jar_contents.txt
jar -tvf /Users/cjoakim/.m2/repository/com/microsoft/azure/azure-cosmosdb-commons/2.2.0/azure-cosmosdb-commons-2.2.0.jar >> doc/jar_contents.txt

echo "JAR-FILE: /Users/cjoakim/.m2/repository/org/apache/commons/commons-collections4/4.2/commons-collections4-4.2.jar" >> doc/jar_contents.txt
jar -tvf /Users/cjoakim/.m2/repository/org/apache/commons/commons-collections4/4.2/commons-collections4-4.2.jar >> doc/jar_contents.txt

echo "JAR-FILE: /Users/cjoakim/.m2/repository/com/microsoft/azure/azure-cosmosdb-gateway/2.2.0/azure-cosmosdb-gateway-2.2.0.jar" >> doc/jar_contents.txt
jar -tvf /Users/cjoakim/.m2/repository/com/microsoft/azure/azure-cosmosdb-gateway/2.2.0/azure-cosmosdb-gateway-2.2.0.jar >> doc/jar_contents.txt

echo "JAR-FILE: /Users/cjoakim/.m2/repository/com/microsoft/azure/azure-cosmosdb-direct/2.2.0/azure-cosmosdb-direct-2.2.0.jar" >> doc/jar_contents.txt
jar -tvf /Users/cjoakim/.m2/repository/com/microsoft/azure/azure-cosmosdb-direct/2.2.0/azure-cosmosdb-direct-2.2.0.jar >> doc/jar_contents.txt

echo "JAR-FILE: /Users/cjoakim/.m2/repository/commons-io/commons-io/2.5/commons-io-2.5.jar" >> doc/jar_contents.txt
jar -tvf /Users/cjoakim/.m2/repository/commons-io/commons-io/2.5/commons-io-2.5.jar >> doc/jar_contents.txt

echo "JAR-FILE: /Users/cjoakim/.m2/repository/com/github/davidmoten/rxjava-extras/0.8.0.17/rxjava-extras-0.8.0.17.jar" >> doc/jar_contents.txt
jar -tvf /Users/cjoakim/.m2/repository/com/github/davidmoten/rxjava-extras/0.8.0.17/rxjava-extras-0.8.0.17.jar >> doc/jar_contents.txt

echo "JAR-FILE: /Users/cjoakim/.m2/repository/io/reactivex/rxjava/1.3.3/rxjava-1.3.3.jar" >> doc/jar_contents.txt
jar -tvf /Users/cjoakim/.m2/repository/io/reactivex/rxjava/1.3.3/rxjava-1.3.3.jar >> doc/jar_contents.txt

echo "JAR-FILE: /Users/cjoakim/.m2/repository/io/reactivex/rxjava-string/1.1.1/rxjava-string-1.1.1.jar" >> doc/jar_contents.txt
jar -tvf /Users/cjoakim/.m2/repository/io/reactivex/rxjava-string/1.1.1/rxjava-string-1.1.1.jar >> doc/jar_contents.txt

echo "JAR-FILE: /Users/cjoakim/.m2/repository/io/reactivex/rxnetty/0.4.20/rxnetty-0.4.20.jar" >> doc/jar_contents.txt
jar -tvf /Users/cjoakim/.m2/repository/io/reactivex/rxnetty/0.4.20/rxnetty-0.4.20.jar >> doc/jar_contents.txt

echo "JAR-FILE: /Users/cjoakim/.m2/repository/io/netty/netty-codec-http/4.1.22.Final/netty-codec-http-4.1.22.Final.jar" >> doc/jar_contents.txt
jar -tvf /Users/cjoakim/.m2/repository/io/netty/netty-codec-http/4.1.22.Final/netty-codec-http-4.1.22.Final.jar >> doc/jar_contents.txt

echo "JAR-FILE: /Users/cjoakim/.m2/repository/io/netty/netty-codec/4.1.22.Final/netty-codec-4.1.22.Final.jar" >> doc/jar_contents.txt
jar -tvf /Users/cjoakim/.m2/repository/io/netty/netty-codec/4.1.22.Final/netty-codec-4.1.22.Final.jar >> doc/jar_contents.txt

echo "JAR-FILE: /Users/cjoakim/.m2/repository/io/netty/netty-handler/4.1.22.Final/netty-handler-4.1.22.Final.jar" >> doc/jar_contents.txt
jar -tvf /Users/cjoakim/.m2/repository/io/netty/netty-handler/4.1.22.Final/netty-handler-4.1.22.Final.jar >> doc/jar_contents.txt

echo "JAR-FILE: /Users/cjoakim/.m2/repository/io/netty/netty-buffer/4.1.22.Final/netty-buffer-4.1.22.Final.jar" >> doc/jar_contents.txt
jar -tvf /Users/cjoakim/.m2/repository/io/netty/netty-buffer/4.1.22.Final/netty-buffer-4.1.22.Final.jar >> doc/jar_contents.txt

echo "JAR-FILE: /Users/cjoakim/.m2/repository/io/netty/netty-common/4.1.22.Final/netty-common-4.1.22.Final.jar" >> doc/jar_contents.txt
jar -tvf /Users/cjoakim/.m2/repository/io/netty/netty-common/4.1.22.Final/netty-common-4.1.22.Final.jar >> doc/jar_contents.txt

echo "JAR-FILE: /Users/cjoakim/.m2/repository/io/netty/netty-transport/4.1.22.Final/netty-transport-4.1.22.Final.jar" >> doc/jar_contents.txt
jar -tvf /Users/cjoakim/.m2/repository/io/netty/netty-transport/4.1.22.Final/netty-transport-4.1.22.Final.jar >> doc/jar_contents.txt

echo "JAR-FILE: /Users/cjoakim/.m2/repository/io/netty/netty-resolver/4.1.22.Final/netty-resolver-4.1.22.Final.jar" >> doc/jar_contents.txt
jar -tvf /Users/cjoakim/.m2/repository/io/netty/netty-resolver/4.1.22.Final/netty-resolver-4.1.22.Final.jar >> doc/jar_contents.txt

echo "JAR-FILE: /Users/cjoakim/.m2/repository/io/netty/netty-handler-proxy/4.1.22.Final/netty-handler-proxy-4.1.22.Final.jar" >> doc/jar_contents.txt
jar -tvf /Users/cjoakim/.m2/repository/io/netty/netty-handler-proxy/4.1.22.Final/netty-handler-proxy-4.1.22.Final.jar >> doc/jar_contents.txt

echo "JAR-FILE: /Users/cjoakim/.m2/repository/io/netty/netty-codec-socks/4.1.22.Final/netty-codec-socks-4.1.22.Final.jar" >> doc/jar_contents.txt
jar -tvf /Users/cjoakim/.m2/repository/io/netty/netty-codec-socks/4.1.22.Final/netty-codec-socks-4.1.22.Final.jar >> doc/jar_contents.txt

echo "JAR-FILE: /Users/cjoakim/.m2/repository/com/microsoft/azure/azure-keyvault/1.1.2/azure-keyvault-1.1.2.jar" >> doc/jar_contents.txt
jar -tvf /Users/cjoakim/.m2/repository/com/microsoft/azure/azure-keyvault/1.1.2/azure-keyvault-1.1.2.jar >> doc/jar_contents.txt

echo "JAR-FILE: /Users/cjoakim/.m2/repository/com/microsoft/azure/azure-keyvault-cryptography/1.1.2/azure-keyvault-cryptography-1.1.2.jar" >> doc/jar_contents.txt
jar -tvf /Users/cjoakim/.m2/repository/com/microsoft/azure/azure-keyvault-cryptography/1.1.2/azure-keyvault-cryptography-1.1.2.jar >> doc/jar_contents.txt

echo "JAR-FILE: /Users/cjoakim/.m2/repository/com/microsoft/azure/azure-keyvault-core/1.1.2/azure-keyvault-core-1.1.2.jar" >> doc/jar_contents.txt
jar -tvf /Users/cjoakim/.m2/repository/com/microsoft/azure/azure-keyvault-core/1.1.2/azure-keyvault-core-1.1.2.jar >> doc/jar_contents.txt

echo "JAR-FILE: /Users/cjoakim/.m2/repository/com/microsoft/azure/azure-keyvault-webkey/1.1.2/azure-keyvault-webkey-1.1.2.jar" >> doc/jar_contents.txt
jar -tvf /Users/cjoakim/.m2/repository/com/microsoft/azure/azure-keyvault-webkey/1.1.2/azure-keyvault-webkey-1.1.2.jar >> doc/jar_contents.txt

echo "JAR-FILE: /Users/cjoakim/.m2/repository/com/microsoft/rest/client-runtime/1.6.1/client-runtime-1.6.1.jar" >> doc/jar_contents.txt
jar -tvf /Users/cjoakim/.m2/repository/com/microsoft/rest/client-runtime/1.6.1/client-runtime-1.6.1.jar >> doc/jar_contents.txt

echo "JAR-FILE: /Users/cjoakim/.m2/repository/com/squareup/okhttp3/logging-interceptor/3.11.0/logging-interceptor-3.11.0.jar" >> doc/jar_contents.txt
jar -tvf /Users/cjoakim/.m2/repository/com/squareup/okhttp3/logging-interceptor/3.11.0/logging-interceptor-3.11.0.jar >> doc/jar_contents.txt

echo "JAR-FILE: /Users/cjoakim/.m2/repository/com/squareup/okhttp3/okhttp-urlconnection/3.11.0/okhttp-urlconnection-3.11.0.jar" >> doc/jar_contents.txt
jar -tvf /Users/cjoakim/.m2/repository/com/squareup/okhttp3/okhttp-urlconnection/3.11.0/okhttp-urlconnection-3.11.0.jar >> doc/jar_contents.txt

echo "JAR-FILE: /Users/cjoakim/.m2/repository/com/squareup/retrofit2/converter-jackson/2.4.0/converter-jackson-2.4.0.jar" >> doc/jar_contents.txt
jar -tvf /Users/cjoakim/.m2/repository/com/squareup/retrofit2/converter-jackson/2.4.0/converter-jackson-2.4.0.jar >> doc/jar_contents.txt

echo "JAR-FILE: /Users/cjoakim/.m2/repository/com/fasterxml/jackson/datatype/jackson-datatype-joda/2.9.4/jackson-datatype-joda-2.9.4.jar" >> doc/jar_contents.txt
jar -tvf /Users/cjoakim/.m2/repository/com/fasterxml/jackson/datatype/jackson-datatype-joda/2.9.4/jackson-datatype-joda-2.9.4.jar >> doc/jar_contents.txt

echo "JAR-FILE: /Users/cjoakim/.m2/repository/com/squareup/retrofit2/adapter-rxjava/2.4.0/adapter-rxjava-2.4.0.jar" >> doc/jar_contents.txt
jar -tvf /Users/cjoakim/.m2/repository/com/squareup/retrofit2/adapter-rxjava/2.4.0/adapter-rxjava-2.4.0.jar >> doc/jar_contents.txt

echo "JAR-FILE: /Users/cjoakim/.m2/repository/com/fasterxml/jackson/core/jackson-annotations/2.9.6/jackson-annotations-2.9.6.jar" >> doc/jar_contents.txt
jar -tvf /Users/cjoakim/.m2/repository/com/fasterxml/jackson/core/jackson-annotations/2.9.6/jackson-annotations-2.9.6.jar >> doc/jar_contents.txt

echo "JAR-FILE: /Users/cjoakim/.m2/repository/com/fasterxml/jackson/core/jackson-core/2.9.6/jackson-core-2.9.6.jar" >> doc/jar_contents.txt
jar -tvf /Users/cjoakim/.m2/repository/com/fasterxml/jackson/core/jackson-core/2.9.6/jackson-core-2.9.6.jar >> doc/jar_contents.txt

echo "JAR-FILE: /Users/cjoakim/.m2/repository/commons-codec/commons-codec/1.10/commons-codec-1.10.jar" >> doc/jar_contents.txt
jar -tvf /Users/cjoakim/.m2/repository/commons-codec/commons-codec/1.10/commons-codec-1.10.jar >> doc/jar_contents.txt

echo "JAR-FILE: /Users/cjoakim/.m2/repository/com/google/guava/guava/20.0/guava-20.0.jar" >> doc/jar_contents.txt
jar -tvf /Users/cjoakim/.m2/repository/com/google/guava/guava/20.0/guava-20.0.jar >> doc/jar_contents.txt

echo "JAR-FILE: /Users/cjoakim/.m2/repository/com/squareup/retrofit2/retrofit/2.4.0/retrofit-2.4.0.jar" >> doc/jar_contents.txt
jar -tvf /Users/cjoakim/.m2/repository/com/squareup/retrofit2/retrofit/2.4.0/retrofit-2.4.0.jar >> doc/jar_contents.txt

echo "JAR-FILE: /Users/cjoakim/.m2/repository/com/squareup/okhttp3/okhttp/3.10.0/okhttp-3.10.0.jar" >> doc/jar_contents.txt
jar -tvf /Users/cjoakim/.m2/repository/com/squareup/okhttp3/okhttp/3.10.0/okhttp-3.10.0.jar >> doc/jar_contents.txt

echo "JAR-FILE: /Users/cjoakim/.m2/repository/com/squareup/okio/okio/1.14.0/okio-1.14.0.jar" >> doc/jar_contents.txt
jar -tvf /Users/cjoakim/.m2/repository/com/squareup/okio/okio/1.14.0/okio-1.14.0.jar >> doc/jar_contents.txt

echo "JAR-FILE: /Users/cjoakim/.m2/repository/com/microsoft/azure/azure-servicebus/1.2.8/azure-servicebus-1.2.8.jar" >> doc/jar_contents.txt
jar -tvf /Users/cjoakim/.m2/repository/com/microsoft/azure/azure-servicebus/1.2.8/azure-servicebus-1.2.8.jar >> doc/jar_contents.txt

echo "JAR-FILE: /Users/cjoakim/.m2/repository/org/bouncycastle/bcpkix-jdk15on/1.53/bcpkix-jdk15on-1.53.jar" >> doc/jar_contents.txt
jar -tvf /Users/cjoakim/.m2/repository/org/bouncycastle/bcpkix-jdk15on/1.53/bcpkix-jdk15on-1.53.jar >> doc/jar_contents.txt

echo "JAR-FILE: /Users/cjoakim/.m2/repository/com/microsoft/azure/adal4j/1.3.0/adal4j-1.3.0.jar" >> doc/jar_contents.txt
jar -tvf /Users/cjoakim/.m2/repository/com/microsoft/azure/adal4j/1.3.0/adal4j-1.3.0.jar >> doc/jar_contents.txt

echo "JAR-FILE: /Users/cjoakim/.m2/repository/com/nimbusds/oauth2-oidc-sdk/5.24.1/oauth2-oidc-sdk-5.24.1.jar" >> doc/jar_contents.txt
jar -tvf /Users/cjoakim/.m2/repository/com/nimbusds/oauth2-oidc-sdk/5.24.1/oauth2-oidc-sdk-5.24.1.jar >> doc/jar_contents.txt

echo "JAR-FILE: /Users/cjoakim/.m2/repository/javax/mail/mail/1.4.7/mail-1.4.7.jar" >> doc/jar_contents.txt
jar -tvf /Users/cjoakim/.m2/repository/javax/mail/mail/1.4.7/mail-1.4.7.jar >> doc/jar_contents.txt

echo "JAR-FILE: /Users/cjoakim/.m2/repository/com/github/stephenc/jcip/jcip-annotations/1.0-1/jcip-annotations-1.0-1.jar" >> doc/jar_contents.txt
jar -tvf /Users/cjoakim/.m2/repository/com/github/stephenc/jcip/jcip-annotations/1.0-1/jcip-annotations-1.0-1.jar >> doc/jar_contents.txt

echo "JAR-FILE: /Users/cjoakim/.m2/repository/net/minidev/json-smart/1.3.1/json-smart-1.3.1.jar" >> doc/jar_contents.txt
jar -tvf /Users/cjoakim/.m2/repository/net/minidev/json-smart/1.3.1/json-smart-1.3.1.jar >> doc/jar_contents.txt

echo "JAR-FILE: /Users/cjoakim/.m2/repository/com/nimbusds/lang-tag/1.4.4/lang-tag-1.4.4.jar" >> doc/jar_contents.txt
jar -tvf /Users/cjoakim/.m2/repository/com/nimbusds/lang-tag/1.4.4/lang-tag-1.4.4.jar >> doc/jar_contents.txt

echo "JAR-FILE: /Users/cjoakim/.m2/repository/com/nimbusds/nimbus-jose-jwt/6.4.2/nimbus-jose-jwt-6.4.2.jar" >> doc/jar_contents.txt
jar -tvf /Users/cjoakim/.m2/repository/com/nimbusds/nimbus-jose-jwt/6.4.2/nimbus-jose-jwt-6.4.2.jar >> doc/jar_contents.txt

echo "JAR-FILE: /Users/cjoakim/.m2/repository/com/microsoft/azure/azure-eventhubs/1.2.1/azure-eventhubs-1.2.1.jar" >> doc/jar_contents.txt
jar -tvf /Users/cjoakim/.m2/repository/com/microsoft/azure/azure-eventhubs/1.2.1/azure-eventhubs-1.2.1.jar >> doc/jar_contents.txt

echo "JAR-FILE: /Users/cjoakim/.m2/repository/com/microsoft/azure/qpid-proton-j-extensions/1.1.0/qpid-proton-j-extensions-1.1.0.jar" >> doc/jar_contents.txt
jar -tvf /Users/cjoakim/.m2/repository/com/microsoft/azure/qpid-proton-j-extensions/1.1.0/qpid-proton-j-extensions-1.1.0.jar >> doc/jar_contents.txt

echo "JAR-FILE: /Users/cjoakim/.m2/repository/org/apache/commons/commons-csv/1.6/commons-csv-1.6.jar" >> doc/jar_contents.txt
jar -tvf /Users/cjoakim/.m2/repository/org/apache/commons/commons-csv/1.6/commons-csv-1.6.jar >> doc/jar_contents.txt

echo "JAR-FILE: /Users/cjoakim/.m2/repository/org/apache/tika/tika-app/1.19.1/tika-app-1.19.1.jar" >> doc/jar_contents.txt
jar -tvf /Users/cjoakim/.m2/repository/org/apache/tika/tika-app/1.19.1/tika-app-1.19.1.jar >> doc/jar_contents.txt

echo "JAR-FILE: /Users/cjoakim/.m2/repository/org/apache/tika/tika-langdetect/1.19.1/tika-langdetect-1.19.1.jar" >> doc/jar_contents.txt
jar -tvf /Users/cjoakim/.m2/repository/org/apache/tika/tika-langdetect/1.19.1/tika-langdetect-1.19.1.jar >> doc/jar_contents.txt

echo "JAR-FILE: /Users/cjoakim/.m2/repository/com/optimaize/languagedetector/language-detector/0.6/language-detector-0.6.jar" >> doc/jar_contents.txt
jar -tvf /Users/cjoakim/.m2/repository/com/optimaize/languagedetector/language-detector/0.6/language-detector-0.6.jar >> doc/jar_contents.txt

echo "JAR-FILE: /Users/cjoakim/.m2/repository/net/arnx/jsonic/1.2.11/jsonic-1.2.11.jar" >> doc/jar_contents.txt
jar -tvf /Users/cjoakim/.m2/repository/net/arnx/jsonic/1.2.11/jsonic-1.2.11.jar >> doc/jar_contents.txt

echo "JAR-FILE: /Users/cjoakim/.m2/repository/com/intellij/annotations/12.0/annotations-12.0.jar" >> doc/jar_contents.txt
jar -tvf /Users/cjoakim/.m2/repository/com/intellij/annotations/12.0/annotations-12.0.jar >> doc/jar_contents.txt

echo "JAR-FILE: /Users/cjoakim/.m2/repository/org/apache/tika/tika-serialization/1.19.1/tika-serialization-1.19.1.jar" >> doc/jar_contents.txt
jar -tvf /Users/cjoakim/.m2/repository/org/apache/tika/tika-serialization/1.19.1/tika-serialization-1.19.1.jar >> doc/jar_contents.txt

echo "JAR-FILE: /Users/cjoakim/.m2/repository/org/apache/tika/tika-xmp/1.19.1/tika-xmp-1.19.1.jar" >> doc/jar_contents.txt
jar -tvf /Users/cjoakim/.m2/repository/org/apache/tika/tika-xmp/1.19.1/tika-xmp-1.19.1.jar >> doc/jar_contents.txt

echo "JAR-FILE: /Users/cjoakim/.m2/repository/com/adobe/xmp/xmpcore/5.1.3/xmpcore-5.1.3.jar" >> doc/jar_contents.txt
jar -tvf /Users/cjoakim/.m2/repository/com/adobe/xmp/xmpcore/5.1.3/xmpcore-5.1.3.jar >> doc/jar_contents.txt

echo "JAR-FILE: /Users/cjoakim/.m2/repository/org/apache/tika/tika-batch/1.19.1/tika-batch-1.19.1.jar" >> doc/jar_contents.txt
jar -tvf /Users/cjoakim/.m2/repository/org/apache/tika/tika-batch/1.19.1/tika-batch-1.19.1.jar >> doc/jar_contents.txt

echo "JAR-FILE: /Users/cjoakim/.m2/repository/commons-cli/commons-cli/1.4/commons-cli-1.4.jar" >> doc/jar_contents.txt
jar -tvf /Users/cjoakim/.m2/repository/commons-cli/commons-cli/1.4/commons-cli-1.4.jar >> doc/jar_contents.txt

echo "JAR-FILE: /Users/cjoakim/.m2/repository/org/slf4j/slf4j-log4j12/1.7.25/slf4j-log4j12-1.7.25.jar" >> doc/jar_contents.txt
jar -tvf /Users/cjoakim/.m2/repository/org/slf4j/slf4j-log4j12/1.7.25/slf4j-log4j12-1.7.25.jar >> doc/jar_contents.txt

echo "JAR-FILE: /Users/cjoakim/.m2/repository/log4j/log4j/1.2.17/log4j-1.2.17.jar" >> doc/jar_contents.txt
jar -tvf /Users/cjoakim/.m2/repository/log4j/log4j/1.2.17/log4j-1.2.17.jar >> doc/jar_contents.txt

echo "JAR-FILE: /Users/cjoakim/.m2/repository/org/slf4j/jcl-over-slf4j/1.7.25/jcl-over-slf4j-1.7.25.jar" >> doc/jar_contents.txt
jar -tvf /Users/cjoakim/.m2/repository/org/slf4j/jcl-over-slf4j/1.7.25/jcl-over-slf4j-1.7.25.jar >> doc/jar_contents.txt

echo "JAR-FILE: /Users/cjoakim/.m2/repository/org/slf4j/jul-to-slf4j/1.7.25/jul-to-slf4j-1.7.25.jar" >> doc/jar_contents.txt
jar -tvf /Users/cjoakim/.m2/repository/org/slf4j/jul-to-slf4j/1.7.25/jul-to-slf4j-1.7.25.jar >> doc/jar_contents.txt

echo "JAR-FILE: /Users/cjoakim/.m2/repository/org/apache/tika/tika-core/1.19.1/tika-core-1.19.1.jar" >> doc/jar_contents.txt
jar -tvf /Users/cjoakim/.m2/repository/org/apache/tika/tika-core/1.19.1/tika-core-1.19.1.jar >> doc/jar_contents.txt

echo "JAR-FILE: /Users/cjoakim/.m2/repository/org/apache/tika/tika-parsers/1.19.1/tika-parsers-1.19.1.jar" >> doc/jar_contents.txt
jar -tvf /Users/cjoakim/.m2/repository/org/apache/tika/tika-parsers/1.19.1/tika-parsers-1.19.1.jar >> doc/jar_contents.txt

echo "JAR-FILE: /Users/cjoakim/.m2/repository/org/glassfish/jaxb/jaxb-core/2.3.0.1/jaxb-core-2.3.0.1.jar" >> doc/jar_contents.txt
jar -tvf /Users/cjoakim/.m2/repository/org/glassfish/jaxb/jaxb-core/2.3.0.1/jaxb-core-2.3.0.1.jar >> doc/jar_contents.txt

echo "JAR-FILE: /Users/cjoakim/.m2/repository/javax/xml/bind/jaxb-api/2.3.0/jaxb-api-2.3.0.jar" >> doc/jar_contents.txt
jar -tvf /Users/cjoakim/.m2/repository/javax/xml/bind/jaxb-api/2.3.0/jaxb-api-2.3.0.jar >> doc/jar_contents.txt

echo "JAR-FILE: /Users/cjoakim/.m2/repository/org/glassfish/jaxb/txw2/2.3.0.1/txw2-2.3.0.1.jar" >> doc/jar_contents.txt
jar -tvf /Users/cjoakim/.m2/repository/org/glassfish/jaxb/txw2/2.3.0.1/txw2-2.3.0.1.jar >> doc/jar_contents.txt

echo "JAR-FILE: /Users/cjoakim/.m2/repository/com/sun/istack/istack-commons-runtime/3.0.5/istack-commons-runtime-3.0.5.jar" >> doc/jar_contents.txt
jar -tvf /Users/cjoakim/.m2/repository/com/sun/istack/istack-commons-runtime/3.0.5/istack-commons-runtime-3.0.5.jar >> doc/jar_contents.txt

echo "JAR-FILE: /Users/cjoakim/.m2/repository/org/glassfish/jaxb/jaxb-runtime/2.3.0.1/jaxb-runtime-2.3.0.1.jar" >> doc/jar_contents.txt
jar -tvf /Users/cjoakim/.m2/repository/org/glassfish/jaxb/jaxb-runtime/2.3.0.1/jaxb-runtime-2.3.0.1.jar >> doc/jar_contents.txt

echo "JAR-FILE: /Users/cjoakim/.m2/repository/org/jvnet/staxex/stax-ex/1.7.8/stax-ex-1.7.8.jar" >> doc/jar_contents.txt
jar -tvf /Users/cjoakim/.m2/repository/org/jvnet/staxex/stax-ex/1.7.8/stax-ex-1.7.8.jar >> doc/jar_contents.txt

echo "JAR-FILE: /Users/cjoakim/.m2/repository/com/sun/xml/fastinfoset/FastInfoset/1.2.13/FastInfoset-1.2.13.jar" >> doc/jar_contents.txt
jar -tvf /Users/cjoakim/.m2/repository/com/sun/xml/fastinfoset/FastInfoset/1.2.13/FastInfoset-1.2.13.jar >> doc/jar_contents.txt

echo "JAR-FILE: /Users/cjoakim/.m2/repository/javax/activation/activation/1.1.1/activation-1.1.1.jar" >> doc/jar_contents.txt
jar -tvf /Users/cjoakim/.m2/repository/javax/activation/activation/1.1.1/activation-1.1.1.jar >> doc/jar_contents.txt

echo "JAR-FILE: /Users/cjoakim/.m2/repository/org/gagravarr/vorbis-java-tika/0.8/vorbis-java-tika-0.8.jar" >> doc/jar_contents.txt
jar -tvf /Users/cjoakim/.m2/repository/org/gagravarr/vorbis-java-tika/0.8/vorbis-java-tika-0.8.jar >> doc/jar_contents.txt

echo "JAR-FILE: /Users/cjoakim/.m2/repository/com/healthmarketscience/jackcess/jackcess/2.1.12/jackcess-2.1.12.jar" >> doc/jar_contents.txt
jar -tvf /Users/cjoakim/.m2/repository/com/healthmarketscience/jackcess/jackcess/2.1.12/jackcess-2.1.12.jar >> doc/jar_contents.txt

echo "JAR-FILE: /Users/cjoakim/.m2/repository/commons-lang/commons-lang/2.6/commons-lang-2.6.jar" >> doc/jar_contents.txt
jar -tvf /Users/cjoakim/.m2/repository/commons-lang/commons-lang/2.6/commons-lang-2.6.jar >> doc/jar_contents.txt

echo "JAR-FILE: /Users/cjoakim/.m2/repository/com/healthmarketscience/jackcess/jackcess-encrypt/2.1.4/jackcess-encrypt-2.1.4.jar" >> doc/jar_contents.txt
jar -tvf /Users/cjoakim/.m2/repository/com/healthmarketscience/jackcess/jackcess-encrypt/2.1.4/jackcess-encrypt-2.1.4.jar >> doc/jar_contents.txt

echo "JAR-FILE: /Users/cjoakim/.m2/repository/org/tallison/jmatio/1.5/jmatio-1.5.jar" >> doc/jar_contents.txt
jar -tvf /Users/cjoakim/.m2/repository/org/tallison/jmatio/1.5/jmatio-1.5.jar >> doc/jar_contents.txt

echo "JAR-FILE: /Users/cjoakim/.m2/repository/org/apache/james/apache-mime4j-core/0.8.2/apache-mime4j-core-0.8.2.jar" >> doc/jar_contents.txt
jar -tvf /Users/cjoakim/.m2/repository/org/apache/james/apache-mime4j-core/0.8.2/apache-mime4j-core-0.8.2.jar >> doc/jar_contents.txt

echo "JAR-FILE: /Users/cjoakim/.m2/repository/org/apache/james/apache-mime4j-dom/0.8.2/apache-mime4j-dom-0.8.2.jar" >> doc/jar_contents.txt
jar -tvf /Users/cjoakim/.m2/repository/org/apache/james/apache-mime4j-dom/0.8.2/apache-mime4j-dom-0.8.2.jar >> doc/jar_contents.txt

echo "JAR-FILE: /Users/cjoakim/.m2/repository/org/apache/commons/commons-compress/1.18/commons-compress-1.18.jar" >> doc/jar_contents.txt
jar -tvf /Users/cjoakim/.m2/repository/org/apache/commons/commons-compress/1.18/commons-compress-1.18.jar >> doc/jar_contents.txt

echo "JAR-FILE: /Users/cjoakim/.m2/repository/org/tukaani/xz/1.8/xz-1.8.jar" >> doc/jar_contents.txt
jar -tvf /Users/cjoakim/.m2/repository/org/tukaani/xz/1.8/xz-1.8.jar >> doc/jar_contents.txt

echo "JAR-FILE: /Users/cjoakim/.m2/repository/com/epam/parso/2.0.9/parso-2.0.9.jar" >> doc/jar_contents.txt
jar -tvf /Users/cjoakim/.m2/repository/com/epam/parso/2.0.9/parso-2.0.9.jar >> doc/jar_contents.txt

echo "JAR-FILE: /Users/cjoakim/.m2/repository/org/brotli/dec/0.1.2/dec-0.1.2.jar" >> doc/jar_contents.txt
jar -tvf /Users/cjoakim/.m2/repository/org/brotli/dec/0.1.2/dec-0.1.2.jar >> doc/jar_contents.txt

echo "JAR-FILE: /Users/cjoakim/.m2/repository/org/apache/pdfbox/pdfbox/2.0.12/pdfbox-2.0.12.jar" >> doc/jar_contents.txt
jar -tvf /Users/cjoakim/.m2/repository/org/apache/pdfbox/pdfbox/2.0.12/pdfbox-2.0.12.jar >> doc/jar_contents.txt

echo "JAR-FILE: /Users/cjoakim/.m2/repository/org/apache/pdfbox/fontbox/2.0.12/fontbox-2.0.12.jar" >> doc/jar_contents.txt
jar -tvf /Users/cjoakim/.m2/repository/org/apache/pdfbox/fontbox/2.0.12/fontbox-2.0.12.jar >> doc/jar_contents.txt

echo "JAR-FILE: /Users/cjoakim/.m2/repository/org/apache/pdfbox/pdfbox-tools/2.0.12/pdfbox-tools-2.0.12.jar" >> doc/jar_contents.txt
jar -tvf /Users/cjoakim/.m2/repository/org/apache/pdfbox/pdfbox-tools/2.0.12/pdfbox-tools-2.0.12.jar >> doc/jar_contents.txt

echo "JAR-FILE: /Users/cjoakim/.m2/repository/org/apache/pdfbox/jempbox/1.8.16/jempbox-1.8.16.jar" >> doc/jar_contents.txt
jar -tvf /Users/cjoakim/.m2/repository/org/apache/pdfbox/jempbox/1.8.16/jempbox-1.8.16.jar >> doc/jar_contents.txt

echo "JAR-FILE: /Users/cjoakim/.m2/repository/org/bouncycastle/bcmail-jdk15on/1.60/bcmail-jdk15on-1.60.jar" >> doc/jar_contents.txt
jar -tvf /Users/cjoakim/.m2/repository/org/bouncycastle/bcmail-jdk15on/1.60/bcmail-jdk15on-1.60.jar >> doc/jar_contents.txt

echo "JAR-FILE: /Users/cjoakim/.m2/repository/org/bouncycastle/bcprov-jdk15on/1.60/bcprov-jdk15on-1.60.jar" >> doc/jar_contents.txt
jar -tvf /Users/cjoakim/.m2/repository/org/bouncycastle/bcprov-jdk15on/1.60/bcprov-jdk15on-1.60.jar >> doc/jar_contents.txt

echo "JAR-FILE: /Users/cjoakim/.m2/repository/org/apache/poi/poi/4.0.0/poi-4.0.0.jar" >> doc/jar_contents.txt
jar -tvf /Users/cjoakim/.m2/repository/org/apache/poi/poi/4.0.0/poi-4.0.0.jar >> doc/jar_contents.txt

echo "JAR-FILE: /Users/cjoakim/.m2/repository/org/apache/poi/poi-scratchpad/4.0.0/poi-scratchpad-4.0.0.jar" >> doc/jar_contents.txt
jar -tvf /Users/cjoakim/.m2/repository/org/apache/poi/poi-scratchpad/4.0.0/poi-scratchpad-4.0.0.jar >> doc/jar_contents.txt

echo "JAR-FILE: /Users/cjoakim/.m2/repository/org/apache/poi/poi-ooxml/4.0.0/poi-ooxml-4.0.0.jar" >> doc/jar_contents.txt
jar -tvf /Users/cjoakim/.m2/repository/org/apache/poi/poi-ooxml/4.0.0/poi-ooxml-4.0.0.jar >> doc/jar_contents.txt

echo "JAR-FILE: /Users/cjoakim/.m2/repository/org/apache/poi/poi-ooxml-schemas/4.0.0/poi-ooxml-schemas-4.0.0.jar" >> doc/jar_contents.txt
jar -tvf /Users/cjoakim/.m2/repository/org/apache/poi/poi-ooxml-schemas/4.0.0/poi-ooxml-schemas-4.0.0.jar >> doc/jar_contents.txt

echo "JAR-FILE: /Users/cjoakim/.m2/repository/org/apache/xmlbeans/xmlbeans/3.0.1/xmlbeans-3.0.1.jar" >> doc/jar_contents.txt
jar -tvf /Users/cjoakim/.m2/repository/org/apache/xmlbeans/xmlbeans/3.0.1/xmlbeans-3.0.1.jar >> doc/jar_contents.txt

echo "JAR-FILE: /Users/cjoakim/.m2/repository/com/github/virtuald/curvesapi/1.04/curvesapi-1.04.jar" >> doc/jar_contents.txt
jar -tvf /Users/cjoakim/.m2/repository/com/github/virtuald/curvesapi/1.04/curvesapi-1.04.jar >> doc/jar_contents.txt

echo "JAR-FILE: /Users/cjoakim/.m2/repository/org/ccil/cowan/tagsoup/tagsoup/1.2.1/tagsoup-1.2.1.jar" >> doc/jar_contents.txt
jar -tvf /Users/cjoakim/.m2/repository/org/ccil/cowan/tagsoup/tagsoup/1.2.1/tagsoup-1.2.1.jar >> doc/jar_contents.txt

echo "JAR-FILE: /Users/cjoakim/.m2/repository/org/ow2/asm/asm/6.2/asm-6.2.jar" >> doc/jar_contents.txt
jar -tvf /Users/cjoakim/.m2/repository/org/ow2/asm/asm/6.2/asm-6.2.jar >> doc/jar_contents.txt

echo "JAR-FILE: /Users/cjoakim/.m2/repository/com/googlecode/mp4parser/isoparser/1.1.22/isoparser-1.1.22.jar" >> doc/jar_contents.txt
jar -tvf /Users/cjoakim/.m2/repository/com/googlecode/mp4parser/isoparser/1.1.22/isoparser-1.1.22.jar >> doc/jar_contents.txt

echo "JAR-FILE: /Users/cjoakim/.m2/repository/com/drewnoakes/metadata-extractor/2.11.0/metadata-extractor-2.11.0.jar" >> doc/jar_contents.txt
jar -tvf /Users/cjoakim/.m2/repository/com/drewnoakes/metadata-extractor/2.11.0/metadata-extractor-2.11.0.jar >> doc/jar_contents.txt

echo "JAR-FILE: /Users/cjoakim/.m2/repository/de/l3s/boilerpipe/boilerpipe/1.1.0/boilerpipe-1.1.0.jar" >> doc/jar_contents.txt
jar -tvf /Users/cjoakim/.m2/repository/de/l3s/boilerpipe/boilerpipe/1.1.0/boilerpipe-1.1.0.jar >> doc/jar_contents.txt

echo "JAR-FILE: /Users/cjoakim/.m2/repository/com/rometools/rome/1.5.1/rome-1.5.1.jar" >> doc/jar_contents.txt
jar -tvf /Users/cjoakim/.m2/repository/com/rometools/rome/1.5.1/rome-1.5.1.jar >> doc/jar_contents.txt

echo "JAR-FILE: /Users/cjoakim/.m2/repository/com/rometools/rome-utils/1.5.1/rome-utils-1.5.1.jar" >> doc/jar_contents.txt
jar -tvf /Users/cjoakim/.m2/repository/com/rometools/rome-utils/1.5.1/rome-utils-1.5.1.jar >> doc/jar_contents.txt

echo "JAR-FILE: /Users/cjoakim/.m2/repository/org/gagravarr/vorbis-java-core/0.8/vorbis-java-core-0.8.jar" >> doc/jar_contents.txt
jar -tvf /Users/cjoakim/.m2/repository/org/gagravarr/vorbis-java-core/0.8/vorbis-java-core-0.8.jar >> doc/jar_contents.txt

echo "JAR-FILE: /Users/cjoakim/.m2/repository/com/googlecode/juniversalchardet/juniversalchardet/1.0.3/juniversalchardet-1.0.3.jar" >> doc/jar_contents.txt
jar -tvf /Users/cjoakim/.m2/repository/com/googlecode/juniversalchardet/juniversalchardet/1.0.3/juniversalchardet-1.0.3.jar >> doc/jar_contents.txt

echo "JAR-FILE: /Users/cjoakim/.m2/repository/org/codelibs/jhighlight/1.0.3/jhighlight-1.0.3.jar" >> doc/jar_contents.txt
jar -tvf /Users/cjoakim/.m2/repository/org/codelibs/jhighlight/1.0.3/jhighlight-1.0.3.jar >> doc/jar_contents.txt

echo "JAR-FILE: /Users/cjoakim/.m2/repository/com/pff/java-libpst/0.8.1/java-libpst-0.8.1.jar" >> doc/jar_contents.txt
jar -tvf /Users/cjoakim/.m2/repository/com/pff/java-libpst/0.8.1/java-libpst-0.8.1.jar >> doc/jar_contents.txt

echo "JAR-FILE: /Users/cjoakim/.m2/repository/com/github/junrar/junrar/2.0.0/junrar-2.0.0.jar" >> doc/jar_contents.txt
jar -tvf /Users/cjoakim/.m2/repository/com/github/junrar/junrar/2.0.0/junrar-2.0.0.jar >> doc/jar_contents.txt

echo "JAR-FILE: /Users/cjoakim/.m2/repository/org/apache/cxf/cxf-rt-rs-client/3.2.6/cxf-rt-rs-client-3.2.6.jar" >> doc/jar_contents.txt
jar -tvf /Users/cjoakim/.m2/repository/org/apache/cxf/cxf-rt-rs-client/3.2.6/cxf-rt-rs-client-3.2.6.jar >> doc/jar_contents.txt

echo "JAR-FILE: /Users/cjoakim/.m2/repository/org/apache/cxf/cxf-rt-transports-http/3.2.6/cxf-rt-transports-http-3.2.6.jar" >> doc/jar_contents.txt
jar -tvf /Users/cjoakim/.m2/repository/org/apache/cxf/cxf-rt-transports-http/3.2.6/cxf-rt-transports-http-3.2.6.jar >> doc/jar_contents.txt

echo "JAR-FILE: /Users/cjoakim/.m2/repository/org/apache/cxf/cxf-core/3.2.6/cxf-core-3.2.6.jar" >> doc/jar_contents.txt
jar -tvf /Users/cjoakim/.m2/repository/org/apache/cxf/cxf-core/3.2.6/cxf-core-3.2.6.jar >> doc/jar_contents.txt

echo "JAR-FILE: /Users/cjoakim/.m2/repository/com/fasterxml/woodstox/woodstox-core/5.1.0/woodstox-core-5.1.0.jar" >> doc/jar_contents.txt
jar -tvf /Users/cjoakim/.m2/repository/com/fasterxml/woodstox/woodstox-core/5.1.0/woodstox-core-5.1.0.jar >> doc/jar_contents.txt

echo "JAR-FILE: /Users/cjoakim/.m2/repository/org/codehaus/woodstox/stax2-api/4.1/stax2-api-4.1.jar" >> doc/jar_contents.txt
jar -tvf /Users/cjoakim/.m2/repository/org/codehaus/woodstox/stax2-api/4.1/stax2-api-4.1.jar >> doc/jar_contents.txt

echo "JAR-FILE: /Users/cjoakim/.m2/repository/org/apache/ws/xmlschema/xmlschema-core/2.2.3/xmlschema-core-2.2.3.jar" >> doc/jar_contents.txt
jar -tvf /Users/cjoakim/.m2/repository/org/apache/ws/xmlschema/xmlschema-core/2.2.3/xmlschema-core-2.2.3.jar >> doc/jar_contents.txt

echo "JAR-FILE: /Users/cjoakim/.m2/repository/org/apache/cxf/cxf-rt-frontend-jaxrs/3.2.6/cxf-rt-frontend-jaxrs-3.2.6.jar" >> doc/jar_contents.txt
jar -tvf /Users/cjoakim/.m2/repository/org/apache/cxf/cxf-rt-frontend-jaxrs/3.2.6/cxf-rt-frontend-jaxrs-3.2.6.jar >> doc/jar_contents.txt

echo "JAR-FILE: /Users/cjoakim/.m2/repository/javax/ws/rs/javax.ws.rs-api/2.1/javax.ws.rs-api-2.1.jar" >> doc/jar_contents.txt
jar -tvf /Users/cjoakim/.m2/repository/javax/ws/rs/javax.ws.rs-api/2.1/javax.ws.rs-api-2.1.jar >> doc/jar_contents.txt

echo "JAR-FILE: /Users/cjoakim/.m2/repository/javax/annotation/javax.annotation-api/1.3/javax.annotation-api-1.3.jar" >> doc/jar_contents.txt
jar -tvf /Users/cjoakim/.m2/repository/javax/annotation/javax.annotation-api/1.3/javax.annotation-api-1.3.jar >> doc/jar_contents.txt

echo "JAR-FILE: /Users/cjoakim/.m2/repository/org/apache/commons/commons-exec/1.3/commons-exec-1.3.jar" >> doc/jar_contents.txt
jar -tvf /Users/cjoakim/.m2/repository/org/apache/commons/commons-exec/1.3/commons-exec-1.3.jar >> doc/jar_contents.txt

echo "JAR-FILE: /Users/cjoakim/.m2/repository/org/apache/opennlp/opennlp-tools/1.9.0/opennlp-tools-1.9.0.jar" >> doc/jar_contents.txt
jar -tvf /Users/cjoakim/.m2/repository/org/apache/opennlp/opennlp-tools/1.9.0/opennlp-tools-1.9.0.jar >> doc/jar_contents.txt

echo "JAR-FILE: /Users/cjoakim/.m2/repository/com/googlecode/json-simple/json-simple/1.1.1/json-simple-1.1.1.jar" >> doc/jar_contents.txt
jar -tvf /Users/cjoakim/.m2/repository/com/googlecode/json-simple/json-simple/1.1.1/json-simple-1.1.1.jar >> doc/jar_contents.txt

echo "JAR-FILE: /Users/cjoakim/.m2/repository/com/github/openjson/openjson/1.0.10/openjson-1.0.10.jar" >> doc/jar_contents.txt
jar -tvf /Users/cjoakim/.m2/repository/com/github/openjson/openjson/1.0.10/openjson-1.0.10.jar >> doc/jar_contents.txt

echo "JAR-FILE: /Users/cjoakim/.m2/repository/com/google/code/gson/gson/2.8.5/gson-2.8.5.jar" >> doc/jar_contents.txt
jar -tvf /Users/cjoakim/.m2/repository/com/google/code/gson/gson/2.8.5/gson-2.8.5.jar >> doc/jar_contents.txt

echo "JAR-FILE: /Users/cjoakim/.m2/repository/edu/ucar/netcdf4/4.5.5/netcdf4-4.5.5.jar" >> doc/jar_contents.txt
jar -tvf /Users/cjoakim/.m2/repository/edu/ucar/netcdf4/4.5.5/netcdf4-4.5.5.jar >> doc/jar_contents.txt

echo "JAR-FILE: /Users/cjoakim/.m2/repository/net/jcip/jcip-annotations/1.0/jcip-annotations-1.0.jar" >> doc/jar_contents.txt
jar -tvf /Users/cjoakim/.m2/repository/net/jcip/jcip-annotations/1.0/jcip-annotations-1.0.jar >> doc/jar_contents.txt

echo "JAR-FILE: /Users/cjoakim/.m2/repository/edu/ucar/grib/4.5.5/grib-4.5.5.jar" >> doc/jar_contents.txt
jar -tvf /Users/cjoakim/.m2/repository/edu/ucar/grib/4.5.5/grib-4.5.5.jar >> doc/jar_contents.txt

echo "JAR-FILE: /Users/cjoakim/.m2/repository/com/google/protobuf/protobuf-java/2.5.0/protobuf-java-2.5.0.jar" >> doc/jar_contents.txt
jar -tvf /Users/cjoakim/.m2/repository/com/google/protobuf/protobuf-java/2.5.0/protobuf-java-2.5.0.jar >> doc/jar_contents.txt

echo "JAR-FILE: /Users/cjoakim/.m2/repository/org/itadaki/bzip2/0.9.1/bzip2-0.9.1.jar" >> doc/jar_contents.txt
jar -tvf /Users/cjoakim/.m2/repository/org/itadaki/bzip2/0.9.1/bzip2-0.9.1.jar >> doc/jar_contents.txt

echo "JAR-FILE: /Users/cjoakim/.m2/repository/net/java/dev/jna/jna/4.3.0/jna-4.3.0.jar" >> doc/jar_contents.txt
jar -tvf /Users/cjoakim/.m2/repository/net/java/dev/jna/jna/4.3.0/jna-4.3.0.jar >> doc/jar_contents.txt

echo "JAR-FILE: /Users/cjoakim/.m2/repository/org/jsoup/jsoup/1.11.3/jsoup-1.11.3.jar" >> doc/jar_contents.txt
jar -tvf /Users/cjoakim/.m2/repository/org/jsoup/jsoup/1.11.3/jsoup-1.11.3.jar >> doc/jar_contents.txt

echo "JAR-FILE: /Users/cjoakim/.m2/repository/edu/ucar/cdm/4.5.5/cdm-4.5.5.jar" >> doc/jar_contents.txt
jar -tvf /Users/cjoakim/.m2/repository/edu/ucar/cdm/4.5.5/cdm-4.5.5.jar >> doc/jar_contents.txt

echo "JAR-FILE: /Users/cjoakim/.m2/repository/edu/ucar/udunits/4.5.5/udunits-4.5.5.jar" >> doc/jar_contents.txt
jar -tvf /Users/cjoakim/.m2/repository/edu/ucar/udunits/4.5.5/udunits-4.5.5.jar >> doc/jar_contents.txt

echo "JAR-FILE: /Users/cjoakim/.m2/repository/org/quartz-scheduler/quartz/2.2.0/quartz-2.2.0.jar" >> doc/jar_contents.txt
jar -tvf /Users/cjoakim/.m2/repository/org/quartz-scheduler/quartz/2.2.0/quartz-2.2.0.jar >> doc/jar_contents.txt

echo "JAR-FILE: /Users/cjoakim/.m2/repository/c3p0/c3p0/0.9.1.1/c3p0-0.9.1.1.jar" >> doc/jar_contents.txt
jar -tvf /Users/cjoakim/.m2/repository/c3p0/c3p0/0.9.1.1/c3p0-0.9.1.1.jar >> doc/jar_contents.txt

echo "JAR-FILE: /Users/cjoakim/.m2/repository/net/sf/ehcache/ehcache-core/2.6.2/ehcache-core-2.6.2.jar" >> doc/jar_contents.txt
jar -tvf /Users/cjoakim/.m2/repository/net/sf/ehcache/ehcache-core/2.6.2/ehcache-core-2.6.2.jar >> doc/jar_contents.txt

echo "JAR-FILE: /Users/cjoakim/.m2/repository/com/beust/jcommander/1.35/jcommander-1.35.jar" >> doc/jar_contents.txt
jar -tvf /Users/cjoakim/.m2/repository/com/beust/jcommander/1.35/jcommander-1.35.jar >> doc/jar_contents.txt

echo "JAR-FILE: /Users/cjoakim/.m2/repository/edu/ucar/httpservices/4.5.5/httpservices-4.5.5.jar" >> doc/jar_contents.txt
jar -tvf /Users/cjoakim/.m2/repository/edu/ucar/httpservices/4.5.5/httpservices-4.5.5.jar >> doc/jar_contents.txt

echo "JAR-FILE: /Users/cjoakim/.m2/repository/org/apache/httpcomponents/httpmime/4.5.6/httpmime-4.5.6.jar" >> doc/jar_contents.txt
jar -tvf /Users/cjoakim/.m2/repository/org/apache/httpcomponents/httpmime/4.5.6/httpmime-4.5.6.jar >> doc/jar_contents.txt

echo "JAR-FILE: /Users/cjoakim/.m2/repository/org/apache/sis/core/sis-utility/0.8/sis-utility-0.8.jar" >> doc/jar_contents.txt
jar -tvf /Users/cjoakim/.m2/repository/org/apache/sis/core/sis-utility/0.8/sis-utility-0.8.jar >> doc/jar_contents.txt

echo "JAR-FILE: /Users/cjoakim/.m2/repository/javax/measure/unit-api/1.0/unit-api-1.0.jar" >> doc/jar_contents.txt
jar -tvf /Users/cjoakim/.m2/repository/javax/measure/unit-api/1.0/unit-api-1.0.jar >> doc/jar_contents.txt

echo "JAR-FILE: /Users/cjoakim/.m2/repository/org/apache/sis/storage/sis-netcdf/0.8/sis-netcdf-0.8.jar" >> doc/jar_contents.txt
jar -tvf /Users/cjoakim/.m2/repository/org/apache/sis/storage/sis-netcdf/0.8/sis-netcdf-0.8.jar >> doc/jar_contents.txt

echo "JAR-FILE: /Users/cjoakim/.m2/repository/org/apache/sis/storage/sis-storage/0.8/sis-storage-0.8.jar" >> doc/jar_contents.txt
jar -tvf /Users/cjoakim/.m2/repository/org/apache/sis/storage/sis-storage/0.8/sis-storage-0.8.jar >> doc/jar_contents.txt

echo "JAR-FILE: /Users/cjoakim/.m2/repository/org/apache/sis/core/sis-feature/0.8/sis-feature-0.8.jar" >> doc/jar_contents.txt
jar -tvf /Users/cjoakim/.m2/repository/org/apache/sis/core/sis-feature/0.8/sis-feature-0.8.jar >> doc/jar_contents.txt

echo "JAR-FILE: /Users/cjoakim/.m2/repository/org/apache/sis/core/sis-referencing/0.8/sis-referencing-0.8.jar" >> doc/jar_contents.txt
jar -tvf /Users/cjoakim/.m2/repository/org/apache/sis/core/sis-referencing/0.8/sis-referencing-0.8.jar >> doc/jar_contents.txt

echo "JAR-FILE: /Users/cjoakim/.m2/repository/org/apache/sis/core/sis-metadata/0.8/sis-metadata-0.8.jar" >> doc/jar_contents.txt
jar -tvf /Users/cjoakim/.m2/repository/org/apache/sis/core/sis-metadata/0.8/sis-metadata-0.8.jar >> doc/jar_contents.txt

echo "JAR-FILE: /Users/cjoakim/.m2/repository/org/opengis/geoapi/3.0.1/geoapi-3.0.1.jar" >> doc/jar_contents.txt
jar -tvf /Users/cjoakim/.m2/repository/org/opengis/geoapi/3.0.1/geoapi-3.0.1.jar >> doc/jar_contents.txt

echo "JAR-FILE: /Users/cjoakim/.m2/repository/edu/usc/ir/sentiment-analysis-parser/0.1/sentiment-analysis-parser-0.1.jar" >> doc/jar_contents.txt
jar -tvf /Users/cjoakim/.m2/repository/edu/usc/ir/sentiment-analysis-parser/0.1/sentiment-analysis-parser-0.1.jar >> doc/jar_contents.txt

echo "JAR-FILE: /Users/cjoakim/.m2/repository/org/apache/uima/uimafit-core/2.2.0/uimafit-core-2.2.0.jar" >> doc/jar_contents.txt
jar -tvf /Users/cjoakim/.m2/repository/org/apache/uima/uimafit-core/2.2.0/uimafit-core-2.2.0.jar >> doc/jar_contents.txt

echo "JAR-FILE: /Users/cjoakim/.m2/repository/org/apache/uima/uimaj-core/2.9.0/uimaj-core-2.9.0.jar" >> doc/jar_contents.txt
jar -tvf /Users/cjoakim/.m2/repository/org/apache/uima/uimaj-core/2.9.0/uimaj-core-2.9.0.jar >> doc/jar_contents.txt

echo "JAR-FILE: /Users/cjoakim/.m2/repository/org/jdom/jdom2/2.0.6/jdom2-2.0.6.jar" >> doc/jar_contents.txt
jar -tvf /Users/cjoakim/.m2/repository/org/jdom/jdom2/2.0.6/jdom2-2.0.6.jar >> doc/jar_contents.txt

echo "JAR-FILE: /Users/cjoakim/.m2/repository/org/apache/pdfbox/jbig2-imageio/3.0.2/jbig2-imageio-3.0.2.jar" >> doc/jar_contents.txt
jar -tvf /Users/cjoakim/.m2/repository/org/apache/pdfbox/jbig2-imageio/3.0.2/jbig2-imageio-3.0.2.jar >> doc/jar_contents.txt

echo "JAR-FILE: /Users/cjoakim/.m2/repository/com/github/jai-imageio/jai-imageio-core/1.4.0/jai-imageio-core-1.4.0.jar" >> doc/jar_contents.txt
jar -tvf /Users/cjoakim/.m2/repository/com/github/jai-imageio/jai-imageio-core/1.4.0/jai-imageio-core-1.4.0.jar >> doc/jar_contents.txt

echo "JAR-FILE: /Users/cjoakim/.m2/repository/org/slf4j/slf4j-simple/1.7.25/slf4j-simple-1.7.25.jar" >> doc/jar_contents.txt
jar -tvf /Users/cjoakim/.m2/repository/org/slf4j/slf4j-simple/1.7.25/slf4j-simple-1.7.25.jar >> doc/jar_contents.txt

echo "JAR-FILE: /Users/cjoakim/.m2/repository/org/mongodb/mongo-java-driver/3.9.0/mongo-java-driver-3.9.0.jar" >> doc/jar_contents.txt
jar -tvf /Users/cjoakim/.m2/repository/org/mongodb/mongo-java-driver/3.9.0/mongo-java-driver-3.9.0.jar >> doc/jar_contents.txt

echo "JAR-FILE: /Users/cjoakim/.m2/repository/redis/clients/jedis/2.9.0/jedis-2.9.0.jar" >> doc/jar_contents.txt
jar -tvf /Users/cjoakim/.m2/repository/redis/clients/jedis/2.9.0/jedis-2.9.0.jar >> doc/jar_contents.txt

echo "JAR-FILE: /Users/cjoakim/.m2/repository/org/apache/commons/commons-pool2/2.4.2/commons-pool2-2.4.2.jar" >> doc/jar_contents.txt
jar -tvf /Users/cjoakim/.m2/repository/org/apache/commons/commons-pool2/2.4.2/commons-pool2-2.4.2.jar >> doc/jar_contents.txt

echo "JAR-FILE: /Users/cjoakim/.m2/repository/com/fasterxml/jackson/core/jackson-databind/2.9.7/jackson-databind-2.9.7.jar" >> doc/jar_contents.txt
jar -tvf /Users/cjoakim/.m2/repository/com/fasterxml/jackson/core/jackson-databind/2.9.7/jackson-databind-2.9.7.jar >> doc/jar_contents.txt

echo "JAR-FILE: /Users/cjoakim/.m2/repository/org/apache/activemq/activemq-all/5.15.7/activemq-all-5.15.7.jar" >> doc/jar_contents.txt
jar -tvf /Users/cjoakim/.m2/repository/org/apache/activemq/activemq-all/5.15.7/activemq-all-5.15.7.jar >> doc/jar_contents.txt

echo "JAR-FILE: /Users/cjoakim/.m2/repository/org/apache/qpid/proton-j/0.29.0/proton-j-0.29.0.jar" >> doc/jar_contents.txt
jar -tvf /Users/cjoakim/.m2/repository/org/apache/qpid/proton-j/0.29.0/proton-j-0.29.0.jar >> doc/jar_contents.txt

echo "JAR-FILE: /Users/cjoakim/.m2/repository/junit/junit/4.12/junit-4.12.jar" >> doc/jar_contents.txt
jar -tvf /Users/cjoakim/.m2/repository/junit/junit/4.12/junit-4.12.jar >> doc/jar_contents.txt

echo "JAR-FILE: /Users/cjoakim/.m2/repository/org/hamcrest/hamcrest-core/1.3/hamcrest-core-1.3.jar" >> doc/jar_contents.txt
jar -tvf /Users/cjoakim/.m2/repository/org/hamcrest/hamcrest-core/1.3/hamcrest-core-1.3.jar >> doc/jar_contents.txt

